name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04.5
  
    steps:
       - uses: actions/checkout@v3
       
       - name: Log in to Docker Hub
         uses: docker/login-action@v2.1.0
         with:
           username: ${{  secrets.DOCKER_USERNAME  }}
           password: ${{  secrets.DOCKER_PASSWORD  }}
  
  

     
